### ISSUE TITLE
安卓release包有没有使用正常的

### ISSUE THREAD

**Issue by PoppinRubo** [jpush/jmessage-flutter-plugin#115]
打包后用不了 超时 PlatformException(871201, Get response timeout,please try again later., )
解决不了 都要放弃了 ， 谁的打包后可以用

**Comment by PoppinRubo** [comment]
折腾了一两周了 ,今天终于发现问题所在，我把解决方案分享给大家希望有所帮助，不要再折腾了，哈哈

主要是因为发布包代码混淆导致的，如下解决

1、在 \android\gradle.properties 文件增加配置

默认是这样

org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true

增加一行变成

org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
#开启额外发布配置
extra-gen-snapshot-options=--obfuscate


2、在 \android\app\proguard-rules.pro 文件增加混淆规则

默认是这样

## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**

增加极光混淆规则变成下面这样

## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**

## 极光混淆规则
-dontoptimize
-dontpreverify
-keepattributes  EnclosingMethod,Signature
-dontwarn cn.jpush.**
-keep class cn.jpush.** { *; }

-dontwarn cn.jiguang.**
-keep class cn.jiguang.** { *; }

-dontwarn cn.jmessage.**
-keep class cn.jmessage.**{ *; }

-keepclassmembers class ** {
    public void onEvent*(**);
}

#========================gson================================
-dontwarn com.google.**
-keep class com.google.gson.** {*;}

#========================protobuf================================
-keep class com.google.protobuf.** {*;}

现在再去打包 发现ok了

**Comment by gj452652749** [comment]
niubility！马上试试！

**Comment by gj452652749** [comment]
Hi，哥们，我跑的就是jmessage-flutter-plugin的example，找不到proguard-rules.pro，新建个可以吗？

**Comment by Muzm** [comment]
![image](https://user-images.githubusercontent.com/18257790/79637433-35808b80-81b2-11ea-9c8a-1b71567fb8b2.png)
老哥你给的proguard-rules.pro有问题

**Comment by Muzm** [comment]
我这样才可以
``` pro
##Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.*

##极光混淆规则
-dontoptimize
-dontpreverify
-keepattributes EnclosingMethod,Signature
-dontwarn cn.jpush.**
-keep class cn.jpush.** { *; }

-dontwarn cn.jiguang.**
-keep class cn.jiguang.** { *; }

-dontwarn cn.jmessage.**
-keep class cn.jmessage.**{ *; }

-keepclassmembers class ** {
public void onEvent*(**);
}

#========================gson================================
-dontwarn com.google.**
-keep class com.google.gson.** {*;}

#========================protobuf================================
-keep class com.google.protobuf.** {*;}
```

**Comment by Muzm** [comment]
不过加了你给的混淆确实能在release版本中使用极光了

**Comment by Muzm** [comment]
@gj452652749 https://medium.com/@swav.kulinski/flutter-and-android-obfuscation-8768ac544421

**Comment by PoppinRubo** [comment]
> 不过加了你给的混淆确实能在release版本中使用极光了

可以就ok

**Comment by PoppinRubo** [comment]
> Hi，哥们，我跑的就是jmessage-flutter-plugin的example，找不到proguard-rules.pro，新建个可以吗？

自己项目一般是有proguard-rules.pro 的 ，  example里面的确实是没有 ，你建一个试试瞧瞧😀😀

**Comment by fengzhenbing** [comment]
@Muzm @PoppinRubo 终于可以了，感谢

**Comment by lhalcyon** [comment]
老哥们, flutter swift也可以引用这个插件吗

**Comment by wd308389182** [comment]
@Muzm  @PoppinRubo  谢谢，谢谢啦！
