### ISSUE TITLE
JMConversationInfo.getHistoryMessages有bug

### ISSUE THREAD

**Issue by tygm** [jpush/jmessage-flutter-plugin#17]
> Future<List> getHistoryMessages({
    @required int from,
    @required int limit,
  }) async {
    List msgs = await JmessageFlutter().getHistoryMessages(
      type: target.targetType,//插件中缺少这个，导致报错NoSuchMethodError
      from: from,
      limit: limit
    );
    return msgs;
  }

**Comment by huangminlinux** [comment]
0.0.9 版本修复了这个问题，可以升级一下。

**Comment by tygm** [comment]
好滴
