### ISSUE TITLE
getHistoryMessages方法android和ios返回的消息列表顺序不一致

### ISSUE THREAD

**Issue by yohom** [jpush/jmessage-flutter-plugin#26]
主要是因为dart端和android端没有isDescend参数，导致ios端的这个参数一直是false。 @huangminlinux <img width="546" alt="9A2899D337B6588477D267E3EA43D53C" src="https://user-images.githubusercontent.com/10418364/55048736-41b81900-5084-11e9-9322-73da32393ba9.png">

**Comment by huangminlinux** [comment]
可以升级到 0.0.13 版本 ，[getHistoryMessages](https://github.com/jpush/jmessage-flutter-plugin/blob/master/documents/APIs.md#gethistorymessages) 接口新增了 isDescend 这个字段。

**Comment by yohom** [comment]
ok，解决了。
