### ISSUE TITLE
iphone X ios 13 正式版 真机崩溃

### ISSUE THREAD

**Issue by jackbbhua** [jpush/jmessage-flutter-plugin#77]
![image](https://user-images.githubusercontent.com/4037703/65750805-d4bd3300-e13b-11e9-9a8d-8e94538331eb.png)

![image](https://user-images.githubusercontent.com/4037703/65750924-0df5a300-e13c-11e9-9eeb-d6ba729695a6.png)

**Comment by jackbbhua** [comment]
没有升级正式版之前 不会有这个问题

**Comment by raoxudong** [comment]
字符串截取错误了！  你是在做什么操作 crash 的？

**Comment by jackbbhua** [comment]
发送信息后就挂了 是我哪里做错了 好像以前是可以的😁

**Comment by jackbbhua** [comment]
是flutter版本有点旧 不支持ios 13 升级过后现在ok了 谢谢哦
