### ISSUE TITLE
能不能增加自建消息，然后发送消息的方法。

### ISSUE THREAD

**Issue by aliyoge** [jpush/jmessage-flutter-plugin#9]
发送消息时要等到消息发送成功才能拿到消息体，这样无法跟踪消息发送中的状态，显示给用户看。

![screen shot 2019-01-21 at 4 08 25 pm](https://user-images.githubusercontent.com/12035097/51460645-fdb04b80-1d96-11e9-901c-30e697daa831.png)

**Comment by huangminlinux** [comment]
ok 下个版本添加这个方法。

**Comment by huangminlinux** [comment]
可以升级到 0.0.7，新增：
- [createMessage](https://github.com/jpush/jmessage-flutter-plugin/blob/master/documents/APIs.md#createmessage)
- [sendMessage](https://github.com/jpush/jmessage-flutter-plugin/blob/master/documents/APIs.md#sendmessage)
